[project]
name = "crewai_one"
version = "0.1.0"
description = "crewAI_one using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "apscheduler>=3.11.2",
    "crewai[tools]==1.7.2",
    "email-validator>=2.3.0",
    "fastapi>=0.127.0",
    "fastapi-sso>=0.17.0",
    "litellm>=1.75.3",
]

[project.scripts]
crewai_one = "crewai_one.main:run"
run_crew = "crewai_one.main:run"
train = "crewai_one.main:train"
replay = "crewai_one.main:replay"
test = "crewai_one.main:test"
run_with_trigger = "crewai_one.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
